import Link from "next/link";
import MarketingNav from "@/components/MarketingNav";

export const metadata = {
  title: "Privacy Policy — AI Workflow Automator",
};

export default function PrivacyPage() {
  return (
    <>
      <MarketingNav />
      <main className="max-w-3xl mx-auto px-6 py-16 text-gray-300">
        <h1 className="text-3xl font-bold text-white mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-500 mb-10">Last updated: May 15, 2025</p>

        <section className="space-y-8 text-sm leading-relaxed">
          <div>
            <h2 className="text-lg font-semibold text-white mb-2">1. Information We Collect</h2>
            <p>We collect the following types of information:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-gray-400">
              <li>
                <strong className="text-gray-300">Account information:</strong> name, email address,
                and password when you register
              </li>
              <li>
                <strong className="text-gray-300">Usage data:</strong> automation configurations,
                workflow runs, lead data you provide or that is generated by automations
              </li>
              <li>
                <strong className="text-gray-300">Payment information:</strong> processed securely
                by our payment providers; we do not store card numbers
              </li>
              <li>
                <strong className="text-gray-300">Technical data:</strong> IP address, browser type,
                device info, and usage logs
              </li>
            </ul>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white mb-2">2. How We Use Your Information</h2>
            <p>We use your information to:</p>
            <ul className="list-disc list-inside mt-2 space-y-1 text-gray-400">
              <li>Provide, operate, and improve the Service</li>
              <li>Process payments and manage subscriptions</li>
              <li>Send transactional emails (account confirmations, billing receipts)</li>
              <li>Respond to support requests</li>
              <li>Detect and prevent fraud or abuse</li>
            </ul>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white mb-2">3. Data Sharing</h2>
            <p>
              We do not sell your personal data. We share data only with trusted service providers
              necessary to operate the Service (e.g., cloud hosting, payment processors, email
              delivery). All providers are bound by confidentiality obligations.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white mb-2">4. Data Retention</h2>
            <p>
              We retain your account data for as long as your account is active or as needed to
              provide the Service. After account deletion, we retain data for up to 30 days before
              permanent deletion, unless required by law to retain longer.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white mb-2">5. Cookies</h2>
            <p>
              We use essential cookies to maintain your session and authentication state. We do not
              use advertising or tracking cookies.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white mb-2">6. Security</h2>
            <p>
              We use industry-standard encryption (TLS in transit, encrypted at rest) to protect
              your data. However, no system is 100% secure and we cannot guarantee absolute security.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white mb-2">7. Your Rights</h2>
            <p>
              Depending on your location, you may have rights to access, correct, delete, or export
              your personal data. To exercise these rights, contact us at the email below. We will
              respond within 30 days.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white mb-2">8. Children&apos;s Privacy</h2>
            <p>
              The Service is not directed to children under 13. We do not knowingly collect personal
              data from children. If you believe we have inadvertently collected such data, contact
              us immediately.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white mb-2">9. Changes to This Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of significant
              changes via email or in-app notice. Continued use after changes constitutes acceptance.
            </p>
          </div>

          <div>
            <h2 className="text-lg font-semibold text-white mb-2">10. Contact</h2>
            <p>
              Privacy questions or requests? Email{" "}
              <a
                href="mailto:support@aiworkflowautomator.com"
                className="text-violet-400 hover:text-violet-300 underline"
              >
                support@aiworkflowautomator.com
              </a>
              .
            </p>
          </div>
        </section>
      </main>

      <footer className="border-t border-gray-800/60 py-10 mt-10">
        <div className="max-w-5xl mx-auto px-6 flex flex-col sm:flex-row items-center justify-between gap-4 text-sm text-gray-500">
          <p>© {new Date().getFullYear()} AI Workflow Automator</p>
          <div className="flex items-center gap-6">
            <Link href="/terms" className="hover:text-gray-300 transition-colors">Terms</Link>
            <Link href="/privacy" className="hover:text-gray-300 transition-colors">Privacy</Link>
            <Link href="/refund" className="hover:text-gray-300 transition-colors">Refunds</Link>
          </div>
        </div>
      </footer>
    </>
  );
}
